---
- name: Create gce webserver instance
  hosts: localhost
  connection: local
  gather_facts: True
  vars:
    service_account_email: test-791@cloud101-221822.iam.gserviceaccount.com
    credentials_file: cloud101-221822-6f4aa7bd3cba.json
    project_id: cloud101-221822
    instance_names: web1,web2,web3
    machine_type: n1-standard-1
    image: centos-7
  tasks:
    - name: Create firewall rule to allow http traffic
      gce_net:
        name: default
        fwname: "my-http-fw-rule"
        allowed: tcp:80
        state: deleted
        src_range: "0.0.0.0/0"
        target_tags: "http-server"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
    - name: Create an instance based on image {{ image }}
      gce:
         instance_names: "{{ instance_names }}"
         zone: us-east1-b
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         state: deleted
         preemptible: true
         tags: http-server,https-server
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         metadata: '{"sshKeys" : "jsanchez860301:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUsngMRAoOkkA3IxTqkY0JKmJKM4Ffush71+sl50BPEa+f16/1iExoSLEece/l/MyBvBpedypwpWh+QVCIZIa9xBTn51ZTqWhj14aGBaLSUn4+SY6YFPgwCDgvZf5Ks8JmO7QNKRwWRWiSaVD1uQ7yiZkUSXzQKXuG/Ohzp2da8ANZJ+ER6NooBux/CU3LDPGOTN+WOmCeRZuhDUtbYkiGx6f7gjqTLzL1vUYsoRY0RP2X2/ohLtUCSZA2PeFzjrGNu9k1xwBDytl8C1NLU3yFjjesBfXHTc0AMXDnYlCRJKH9YyufrhQEpApUP8SiM3//LXE3ML1oXSbxaBao7cEpPw0Zu5BfbE2mqPYSOM7PZD2J+WOu+ppIVYo9gUG2x3C4izVt+v3qI942VpnQpwtPIoLZQdfkk8wYcSc4qJ1Efw5UWTKYqbM+RLmEV5IDZVtGt5iuhJSoJL1bkGFrbCkl+XDYpG8W1oerH877Ug1XUYGyFZNbvBYuQflVetqpAiITFJ2BgfncYmEdu6LA64BKYwc5Mnr9RZTocgFjfeR1LD0zTuWwrqCjbvIIlGPaoOK2Cv1BoCll6e8DNRZmDOrZuKD3Y7+m4ZLaR5QsgvXZHPlcwukJU+pSuFGDeDR9oFy/VhQpMpilyMO024L8YSCFlV5hmO3+7eKzZ1uSyiO54Q== javo@srv4.tsmx.lab" }'
      register: gce

    - name: Save host data within a Group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_temp
      with_items: "{{ gce.instance_data }}"
    
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip}} port=22 delay=10 timeout=60
      with_items: "{{ gce.instance_data }}"
      
    - name: setting fact
      set_fact: host={{ item.public_ip }}
      with_items: "{{ gce.instance_data }}"

- name: Configure instance post-creation
  hosts: gce_instances_temp
  gather_facts: True
  remote_user: jsanchez860301
  become: yes
  become_method: sudo
  roles:
      - myapache
