---
- name: Playbook test to create gce instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_email: test-791@cloud101-221822.iam.gserviceaccount.com
    credentials_file: cloud101-221822-6f4aa7bd3cba.json 
    project_id: cloud101-221822
    machine_type: n1-standard-1
    image: centos-7
    zone: us-east1-b
  tasks:
    - name: Lauch instances
      gce:
        instance_names: test1
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        zone: "{{ zone }}"
        metadata: '{"sshKeys" : "jsanchez860301:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUsngMRAoOkkA3IxTqkY0JKmJKM4Ffush71+sl50BPEa+f16/1iExoSLEece/l/MyBvBpedypwpWh+QVCIZIa9xBTn51ZTqWhj14aGBaLSUn4+SY6YFPgwCDgvZf5Ks8JmO7QNKRwWRWiSaVD1uQ7yiZkUSXzQKXuG/Ohzp2da8ANZJ+ER6NooBux/CU3LDPGOTN+WOmCeRZuhDUtbYkiGx6f7gjqTLzL1vUYsoRY0RP2X2/ohLtUCSZA2PeFzjrGNu9k1xwBDytl8C1NLU3yFjjesBfXHTc0AMXDnYlCRJKH9YyufrhQEpApUP8SiM3//LXE3ML1oXSbxaBao7cEpPw0Zu5BfbE2mqPYSOM7PZD2J+WOu+ppIVYo9gUG2x3C4izVt+v3qI942VpnQpwtPIoLZQdfkk8wYcSc4qJ1Efw5UWTKYqbM+RLmEV5IDZVtGt5iuhJSoJL1bkGFrbCkl+XDYpG8W1oerH877Ug1XUYGyFZNbvBYuQflVetqpAiITFJ2BgfncYmEdu6LA64BKYwc5Mnr9RZTocgFjfeR1LD0zTuWwrqCjbvIIlGPaoOK2Cv1BoCll6e8DNRZmDOrZuKD3Y7+m4ZLaR5QsgvXZHPlcwukJU+pSuFGDeDR9oFy/VhQpMpilyMO024L8YSCFlV5hmO3+7eKzZ1uSyiO54Q== javo@srv4.tsmx.lab" }'
